First failing spec
"Error: Cannot find module './string_num_sum'" -- we are trying to
require a module that does not exist.

Normally I don't commit failing specs, but I thought it would be
interesting for someone to be able to read through this repository
commit by commit if they so desired.